/** Georgia Southern University Course Search
 ** suggest_data.js
 ** This file includes arrays to be used by the jQuery
 ** Autocomplete plugin and called in search.js during
 ** the $(document).ready() event. It is updated in the
 ** same manner that form_vars.php is updated.
 */

/* Things included here:
 * Course Subjects and Instructors.
 */
 

var courseSubjects = [
  "AAST",
  "ACCT",
  "AL",
  "AMST",
  "ANTH",
  "ARAB",
  "ART",
  "ARTH",
  "ASTR",
  "BIOL",
  "BIOS",
  "BUSA",
  "CENG",
  "CHBE",
  "CHEM",
  "CHFD",
  "CHIN",
  "CIED",
  "CISM",
  "COED",
  "COHE",
  "COML",
  "COMM",
  "COMS",
  "COOP",
  "COUN",
  "CRJU",
  "CSCI",
  "ECED",
  "ECON",
  "EDAT",
  "EDCI",
  "EDET",
  "EDLD",
  "EDMS",
  "EDMT",
  "EDRD",
  "EDSC",
  "EDUC",
  "EDUF",
  "EDUR",
  "EENG",
  "EGC",
  "ENGL",
  "ENGR",
  "ENVH",
  "ENVS",
  "EPID",
  "EPRS",
  "EPSF",
  "EPY",
  "ESED",
  "ESL",
  "ESPY",
  "ETEC",
  "EURO",
  "FACS",
  "FILM",
  "FINC",
  "FMAD",
  "FORL",
  "FRCT",
  "FREC",
  "FREN",
  "FRER",
  "FRIT",
  "FRLT",
  "FRMS",
  "FYE",
  "GCM",
  "GEOG",
  "GEOL",
  "GRMN",
  "GSOU",
  "GSU",
  "HIST",
  "HLTH",
  "HNRM",
  "HSPM",
  "HUMN",
  "IDS",
  "INDS",
  "INTS",
  "IRSH",
  "ISCI",
  "IT",
  "ITEC",
  "JAPN",
  "KINS",
  "LAST",
  "LATN",
  "LEAD",
  "LESP",
  "LING",
  "LOGT",
  "LSCM",
  "LSTD",
  "MATH",
  "MENG",
  "MFGE",
  "MGED",
  "MGMS",
  "MGNT",
  "MKTG",
  "MMFP",
  "MMJ",
  "MSCI",
  "MSED",
  "MUSA",
  "MUSC",
  "MUSE",
  "NTFS",
  "NURS",
  "PBAD",
  "PHIL",
  "PHLD",
  "PHYS",
  "POLS",
  "PRCA",
  "PSYC",
  "PSYG",
  "PUBH",
  "READ",
  "RECR",
  "RELS",
  "SCED",
  "SEAC",
  "SEGC",
  "SERD",
  "SMGT",
  "SOAR",
  "SOCI",
  "SPAN",
  "SPED",
  "STAT",
  "SUST",
  "TCGT",
  "TCM",
  "TEET",
  "THEA",
  "TMAE",
  "TMFG",
  "TSEC",
  "TSLE",
  "UHON",
  "WBIT",
  "WGST",
  "WLST",
  "WMAC",
  "WMBA",
  "WRIT",
  "YORU"];

var courseInstructors = [
  "Aasheim, Cheryl",
  "Abbott, Lisa",
  "Abbott, Susan",
  "Abell, Martha",
  "Abreu, Christina",
  "Adamos, Maria",
  "Adams, Angela",
  "Adefope, Olufunke",
  "Adeyeye, Samuel",
  "Adhikari, Atin",
  "Afriyie-Gyawu, Evans",
  "Aggarwal, Neelam",
  "Agiato, Elizabeth",
  "Agnich, Laura",
  "Ahad, Mohammad",
  "Aiken, Karelle",
  "Akcaoglu, Mete",
  "Akturk, Ahmet",
  "Alba-Flores, Maria",
  "Albertson, Kathy",
  "Alfonso, Moya",
  "Alhawsali, Abdulrahma",
  "Allen, Andrew",
  "Allen, Deborah",
  "Aller, Monique",
  "Alley, David",
  "Allison, William",
  "Altman, Heidi",
  "Altman, Pamela",
  "Amaral, Heather",
  "Amari, Ibrahim",
  "Amarie, Dragos",
  "Amarie, Olga",
  "Amonette, Allison",
  "Amponsah, William",
  "Amy, Lori",
  "Anderson, Craig",
  "Anderson, Dustin",
  "Anderson, Thomas",
  "Andrews, Urkovia",
  "Apenteng, Bettye",
  "Arrington, Nancy",
  "Aslan, Asli",
  "Aumack, Craig",
  "Avant, Bruce",
  "Bae, Beom",
  "Baev, Simon",
  "Bailey, Sara",
  "Baldwin, Kathleen",
  "Ballagh, Amy",
  "Balleck, Barry",
  "Banter, John",
  "Barilla, Anthony",
  "Barkoulas, Ioannis",
  "Barnes, Meagan",
  "Barrs, Sharon",
  "Bartels, Jean",
  "Bass, Rachel",
  "Batchelor, Robert",
  "Bauer, Danny",
  "Baugh, Michael",
  "Baughman, Logan",
  "Bazemore, Tracey",
  "Beck, Scott",
  "Bedore, Christine",
  "Beebe Novotny, Theresa",
  "Bell, Deborah",
  "Bell, Jeremy",
  "Bell, Zebulon",
  "Benko, Riley",
  "Bennett, Carole",
  "Bennett, Mary",
  "Berecz, Donald",
  "Berger, Andrew",
  "Berry, Kelly",
  "Bhattacharya, Srobana",
  "Biebuyck, William",
  "Bielski, Sarah",
  "Bigley, James",
  "Bilodeau, Thomas",
  "Bingham, Nicholas",
  "Black, Rebecca",
  "Blackburn, Christophe",
  "Blackwell, Brenda",
  "Blair, Amber",
  "Bland, Helen",
  "Boakye, Kwabena",
  "Bodily, Kent",
  "Bodkin, Candice",
  "Bodur, Yasar",
  "Boehmer, Kelly",
  "Boone, Robert",
  "Bos, Monique",
  "Bossler, Adam",
  "Bourdouvalis, Christos",
  "Bourland-Davis, Pamela",
  "Boyer, Ty",
  "Boyter, Joel",
  "Bradley, David",
  "Braselton, James",
  "Braselton, Lorraine",
  "Brent, John",
  "Bridges, Shana",
  "Briggs, Beverly",
  "Brimeyer, Ted",
  "Brinson, Paul",
  "Brkich, Katie",
  "Broadway, Camille",
  "Brock, Gregory",
  "Brooks, Abby",
  "Brooks, Jessica",
  "Brown, Christophe",
  "Brown, Florence",
  "Brown, John",
  "Brown, Sally",
  "Brown, Susan",
  "Brown, Terri",
  "Bruce, Philip",
  "Brunt, Christophe",
  "Bryan, Carolyn",
  "Bryant, Jonathan",
  "Buck, Lauren",
  "Buckhoff, Thomas",
  "Bullington, Joseph",
  "Burdette, Glenn",
  "Burke, Jessica",
  "Burns, Courtney",
  "Burson, Jeffrey",
  "Butterfield, Elizabeth",
  "Buzo Salas, Teresa",
  "Bykowski, Richard",
  "Caciula, Manuela-Cr",
  "Cai, Min",
  "Cairney, Timothy",
  "Calamas, David",
  "Calhoun, Daniel",
  "Campbell, Constance",
  "Caplinger, Christophe",
  "Carden, Stephen",
  "Carey, Sheri",
  "Carrion, Melissa",
  "Carroll, Gwendolyn",
  "Carroll, John",
  "Carroll, Millicent",
  "Carter, Patricia",
  "Case, Thomas",
  "Cason, Susan",
  "Cawthorn, Michelle",
  "Celebi, Hadiye (He",
  "Chambers, Wendy",
  "Chamblee, Gregory",
  "Champ, Charles",
  "Chandler, C",
  "Chang, Guanghsu",
  "Chapman, Daniel",
  "Charlier, Steven",
  "Chatterjee, Arpita",
  "Chen, Lei",
  "Chen, Yunfeng",
  "Chen, Zhan",
  "Chiang, Chung-Yean",
  "Choi, JungHun",
  "Chopak-Foss, Joanne",
  "Chowdhury, Wasimul",
  "Christian, Philip",
  "Cionitti, Linda",
  "Cisternino, Emily",
  "Clark, Jeffrey",
  "Clark-Hubbard, Demita",
  "Clements, Cameron",
  "Cleveland, Richard",
  "Clevenger, Jessica",
  "Clouse, Robert",
  "Cobos, Alba",
  "Cofer, Caitlyn",
  "Coggins, Katelyn",
  "Coggins, William",
  "Cohen, Adrienne",
  "Cohen, Risa",
  "Coleman, Justine",
  "Collins, Linda",
  "Colon-Gaud, Jose",
  "Colquitt, Gavin",
  "Compton, Jonathan",
  "Cone, Diana",
  "Conrad, Rebecca",
  "Cook, Karen",
  "Cook, Kevin",
  "Cooper, Tonya",
  "Copeland, Maura",
  "Cornejo Happel, Claudia",
  "Costello, Lisa",
  "Costomiris, Robert",
  "Counts, Carole",
  "Cowan, Kelley",
  "Cox, Christian",
  "Cox, Don",
  "Crawford, Kathleen",
  "Crofts, Elizabeth",
  "Cromley, Jamie",
  "Cross Mokdad, Dorthie",
  "Cross, Marcia",
  "Cubas Suazo, Francisco",
  "Cuellar, Michael",
  "Cummings, Dean",
  "Curry, Brett",
  "Curtis, Finbarr",
  "Cutler, Christophe",
  "Cyr, Marc",
  "Czech, Daniel",
  "Czech, Michael",
  "Dai, Bo",
  "Dale, Janet",
  "Davis, James",
  "Davis, Lisa",
  "Davis, Rebecca",
  "Davis, Sarah",
  "Davis, Trenton",
  "Davis, Tyson",
  "Davoud, Mohammad",
  "Dazkir, Sibel",
  "De, Pradipta",
  "Deal, S.",
  "Deal, Tony",
  "Dean, Cleon",
  "Delva, Ray",
  "Denmark, Lisa",
  "Denton, Luther",
  "Desai, Anoop",
  "Desiderio, Francis",
  "Dhakal, Robin",
  "DiCesare, John",
  "DiGregorio, Nikki",
  "Diamanduros, Andrew",
  "Diamanduros, Terry",
  "Dickens, Kristen",
  "Dickens, Theodore",
  "Diedesch, Timothy",
  "Dillies, Jimmy",
  "Disney, Andria",
  "Dmitriyev, Grigory",
  "Dobbs, Spencer",
  "Dobson, John",
  "Dotson, Barry",
  "Douberly, Julie",
  "Dove, Meghan",
  "Dowis, William",
  "Downs, Alan",
  "Downs, Elizabeth",
  "Draper, Christine",
  "Drevlow, Benjamin",
  "Dryden, John",
  "Dubert, Christy",
  "Dudley, David",
  "Duggar, Theresa",
  "Dunbar, Matthew",
  "Dunham, Robert",
  "Durach, Maxim",
  "Durant, Jillian",
  "Durden, Lance",
  "Dyer, John",
  "Eastman, Jacqueline",
  "Eastman, Kevin",
  "Eaton, William",
  "Edds, Crystal",
  "Edenfield, Olivia",
  "Eder, Andrea",
  "Edwards, Bradley",
  "Edwards, Elizabeth",
  "Edwards, Inna",
  "Edwards, Mark",
  "Egan, Jessica",
  "Egan, John",
  "Eisenhart, Emily",
  "Eisenhart, Nanette",
  "Eisenreich, Heidi",
  "Elisha, Larisa",
  "Elisha, Steven",
  "Ellis, Amie",
  "Ellis, Eleanor",
  "Ellis, Scott",
  "Elmozughi, Ali",
  "Ems-Bleneau, Virginie",
  "Engel, Steven",
  "Eremeeva, Marina",
  "Espe, Zachary",
  "Fallin, Matt",
  "Fallon, Katherine",
  "Fang, Quentin",
  "Farber, Robert",
  "Farmer, Nathan",
  "Feltman, Brian",
  "Fischer, Charles",
  "Fisher, Karin",
  "Flanigan, Nadia",
  "Fletcher, Leslie",
  "Flynn, Matthew",
  "Flynn, Richard",
  "Ford, Amanda",
  "Fortenberry, Lauren",
  "Fortenberry, Ryan",
  "Fox, Michael",
  "Foxx, Scott",
  "Franks, Logan",
  "Franks, Susan",
  "Fu, Yuzhu",
  "Fung, Chun Hai",
  "Furlong, Jennifer",
  "Furr, Howard",
  "Furry, Stephanie",
  "Futch, Sally Mari",
  "Gambill, Alexander",
  "Gao, Liping",
  "Garcia, Miguel",
  "Gardiner, Adrian",
  "Garlen, Julie",
  "Garno, Melissa",
  "Garvin, Cheryl",
  "Gato, Worlanyo",
  "Gayan, Melissa",
  "Gee, Rose",
  "Gendelman, Juan",
  "George, Sophie",
  "Germani, Gina",
  "Geyerman, Chris",
  "Ghosh, Debanjana",
  "Gibson, Meghann",
  "Giles, Timothy",
  "Gipson, Christina",
  "Glaze, Amanda",
  "Gleason, Daniel",
  "Gong, Haijun",
  "Gonzalez-Rodriguez, Ana",
  "Goodman, Janet",
  "Gould, Laurie",
  "Gracia, Robert",
  "Graf, Annie",
  "Graham, Beverly",
  "Gray, Daniel",
  "Green, James",
  "Green, Lucilia",
  "Greenway, Roy",
  "Gregg, Katy",
  "Gregory, Arikka",
  "Griffin, Bryan",
  "Griffin, David",
  "Griffin, Julia",
  "Griffin, Marlynn",
  "Griffin, Tracey",
  "Grimes, Sara",
  "Groover, Michelle",
  "Grossmann, Axel",
  "Grubb, Jonathan",
  "Grubb, Leah",
  "Gruben, Kathleen",
  "Guggino, Steve",
  "Gutierrez, Antonio",
  "Haberland, Michelle",
  "Hackney, Amy",
  "Haddad, Rami",
  "Hairston, Stephanie",
  "Halaby, Dominique",
  "Hall, Alice",
  "Hall, Eric",
  "Hallman, Suzanne",
  "Hamilton, Ellen",
  "Han, Hyo-Joo",
  "Hancock, Kyle",
  "Hancock, Sarah",
  "Haney, Joshua",
  "Hanna, Christan",
  "Hanna, Mark",
  "Hanna, Reed",
  "Hanschke, Josephine",
  "Hansen, Andrew",
  "Haralson, John",
  "Harp, Spencer",
  "Harper, Steven",
  "Harper, Tamara",
  "Harris, Brandonn",
  "Harris, James",
  "Harris, Kymberly",
  "Harrison, John",
  "Harter, Charles",
  "Harvey, Alan",
  "Harwood, Gregory",
  "Hashiguchi, Matthew",
  "Hatem, John",
  "Hawkins, Kristen",
  "Hawkins, Spencer",
  "He, Ming Fang",
  "Hedrick, Amanda",
  "Heller, Clayton",
  "Henderson, Allen",
  "Henderson, Ann",
  "Hendrix, Ellen",
  "Hendry, Barbara",
  "Hernandez, Maria",
  "Hidalgo, Jose",
  "Higdon, James",
  "Higdon, Sarah",
  "Higgerson, Robert",
  "Higgs, Haley",
  "Hill, Deborah",
  "Hill, Elsie",
  "Hilpert, Jonathan",
  "Hines, Jessica",
  "Hladik, Christine",
  "Hodges, Charles",
  "Hoekzema, Abbey",
  "Hoell, Jacqueline",
  "Hoell, Robert",
  "Hoelscher, Jason",
  "Hollandsworth, Randall",
  "Holley, William",
  "Holmes, Jasmine",
  "Holmes, William",
  "Holtzman, Nicholas",
  "Hooten, Kyle",
  "Hotchkiss, Anna",
  "Howell, Laura",
  "Howerter, Catherine",
  "Hoyle, Justin",
  "Hu, Yi",
  "Huffling, Lacey",
  "Hughes, Martha",
  "Huling, Heather",
  "Hunt, Brandon",
  "Hunt, Tamerah",
  "Hurst, Lorri",
  "Hurst, Michael",
  "Hutcheson, Alyssa",
  "Hutcheson, Kathleen",
  "Hyman, Harvey",
  "ILie, Marcel",
  "Iacob, Alina",
  "Iacob, Ionut",
  "Irby, William",
  "Jackson, Chester",
  "Jackson, Nathaniel",
  "Jackson, Robert",
  "Jacobs, Nancy",
  "Jallow, Saba",
  "James, Natalie",
  "Jeffers, Patrick",
  "Jeffreys, Carla",
  "Jenkins, Toby",
  "Jensen, Devon",
  "Jensen, Lucas",
  "Jeong, Myung",
  "Jersey, Cynthia",
  "Jiang, David",
  "Jin, Yiming",
  "Johnson, Abby",
  "Johnson, Catherine",
  "Johnson, Cynthia",
  "Johnson, Eric",
  "Jones, Jeffery",
  "Jones, Ronnie",
  "Jones, Stephanie",
  "Jordan, Erin",
  "Jovanovic, Vladan",
  "Joye, Shauna",
  "Joyner, June",
  "Jupp, James",
  "Kadlec, Christophe",
  "Kaleta, Jeffrey",
  "Kang, Jun Suk",
  "Kardel, Kamran",
  "Kartchner, Eric",
  "Kasay, Valerie",
  "Kazi, Tahseen",
  "Keane, Drew",
  "Keeley, Howard",
  "Kelly, Jacque",
  "Kennedy, Jodi",
  "Kennedy, Joshua",
  "Kennerly, Rebecca",
  "Kessel, Diane",
  "Khan, Mujiburrah",
  "Kim, Jin Woo",
  "Kim, Jintae",
  "Kim, Seonghoon",
  "Kim, Yoon",
  "Kimball, Lewis",
  "Kimsey, Linda",
  "King, Amanda",
  "King, Barbara",
  "King, John",
  "Kintzinger, Timothy",
  "Kjonnerod, Erik",
  "Klibert, Jeffrey",
  "Kluge, Stacy",
  "Knowles, Donald",
  "Koballa, Thomas",
  "Kocerha, Rebecca",
  "Koehler, Brian",
  "Kolbe, Noriko",
  "Kondo, Chelda",
  "Koricho, Ermias",
  "Kowalewski, Jennifer",
  "Kraeger, Patricia",
  "Kropp, Jerri",
  "Kuenzi, Kerry",
  "Kundu, Gautam",
  "Kung, Hsiang-Jui",
  "Kurkcuoglu, Doga",
  "Kurz, Horst",
  "Kuykendall, Julie",
  "LaFrance, Jason",
  "Lachica-Muschett, Lauren",
  "Lake, Robert",
  "Lakuriqi, Enkeleida",
  "Lambeth, Dawn",
  "Landers, Eric",
  "Landge, Shainaz",
  "Landry, Keith",
  "Langdon, Jody",
  "Langley, David",
  "Lanier, Susie",
  "Larson, Derek",
  "Larson, Lindsay",
  "Larson, Rebecca",
  "Lashbaugh-Barney, Bridget",
  "Lawrence, Raymona",
  "Leckie, Alisa",
  "Lee, Allissa",
  "Lee, Bridgett",
  "Lee, Eun Bae",
  "Lee, Hyun-Woo",
  "Lee, Knicole",
  "Lee, Martha",
  "Lee, Valya",
  "Lee, YoungJoo",
  "Leege, Lissa",
  "Lemon, Christina",
  "Lennon, Sean",
  "Lesaja, Goran",
  "Levernier, William",
  "Lewis, Johanne",
  "Lewis, Nikiya",
  "Li, Jinrong",
  "Li, Li",
  "Li, Lili",
  "Li, Lixin",
  "Li, Mimi",
  "Li, Ru",
  "Li, Xiezhang",
  "Li, Youming",
  "Lim, Sungkyun",
  "Lin, Mao",
  "Lin, Yi",
  "Lindsey, Peggy",
  "Liston, Delores",
  "Littrell, Linda",
  "Liu, Jun",
  "LoBue, James",
  "LoBue, Nan",
  "Locker, Lawrence",
  "Lomax, George",
  "Loper, Brandon",
  "Lubecki, Jacek",
  "Luckett, Brian",
  "Lutzenberger, Eric",
  "Ma, Li",
  "MacKinnon, Ronald",
  "Mackelprang, Alan",
  "Macker, Rebekah",
  "Maghiar, Marcel",
  "Magnant, Colton",
  "Magnant, Zhuojun",
  "Majumdar, Santanu",
  "Malcom, Nancy",
  "Maldonado, Gustavo",
  "Manoosingh, Celine",
  "Marina, Brenda",
  "Marsh, Burney",
  "Marsh, Troy",
  "Martin, Clinton",
  "Martinez, James",
  "Martinez, Valerie",
  "Mase, William",
  "Mason, Richard",
  "Mathews, Ashley",
  "Maurer, Trent",
  "Maxoutopoulis, Kortnie",
  "May, Kathleen",
  "McBrayer, Juliann",
  "McBrayer, Lance",
  "McCall, Rebecca",
  "McCardle, Jie",
  "McCarroll, Sarah",
  "McCollum, Starla",
  "McCurdy, Karen",
  "McDonough, Claire",
  "McGibony, Catherine",
  "McGrath, Leticia",
  "McGrath, Michael",
  "McGuire, Julie",
  "McIlvain, Michael",
  "McKay, Britton",
  "McKenna, Beverly",
  "McLain, Denson",
  "McLemore, Donald",
  "McMillan, James",
  "McMullen, Emerson",
  "McNeal, Heather",
  "McNeal, Ryan",
  "McNutt, Ryan",
  "McPhail, Gin",
  "Medidi, Muralidhar",
  "Melton, Bridget",
  "Melton, Teri",
  "Mercer, Katie",
  "Metrejean, Cheryl",
  "Metrejean, Paul",
  "Michalski, Grzegorz",
  "Miller, April",
  "Miller, Bryan",
  "Miller, Rex",
  "Mirkouei, Amin",
  "Mitchell, Christy",
  "Mitra, Aditi",
  "Mitra, Aniruddha",
  "Moazzam, Mohammadha",
  "Molina, Gustavo",
  "Mondor, Edward",
  "Monetti, David",
  "Moody, Brandi",
  "Mooney, Julian",
  "Moore, DaNell",
  "Moore, Michael",
  "Moore, Sue",
  "Morris, Marla",
  "Mortensen, Hans",
  "Moss, Janet",
  "Moss, Steven",
  "Mossholder, Margaret",
  "Moulton, Marc",
  "Mueller, Stefan",
  "Mullen, Linda",
  "Muller, Lisa",
  "Munkasy, Barry",
  "Murray, David",
  "Murray, Nicholas",
  "Murrieta Colorado, Daniela",
  "Mutchler, Jessica",
  "Mycofsky, Leah",
  "Myers, Mary",
  "Nag, Ananya",
  "Narendrapurapu, Beulah",
  "Nasseh, Saeed",
  "Naufel, Karen",
  "Navaee, Shahnam",
  "Ndaluka, Christina",
  "Nelson, Claire",
  "Neupane, Kishan",
  "Newell, Emily",
  "Newell, Nicholas",
  "Newkirk, April",
  "Newsome, Ashlee",
  "Nguyen, Ha",
  "Nielsen, Michael",
  "Nielsen, Sheila",
  "Noel, David",
  "Noone, Patricia",
  "Norton, William",
  "Novotny, Patrick",
  "O'Malley, John",
  "O'Neill, Johnathan",
  "Oakley, Melissa",
  "Ogburn, Julie",
  "Ogloblin, Constantin",
  "Oliveira Pires, Larissa",
  "Olliff, Edie",
  "Olson, Christina",
  "Oluyede, Broderick",
  "Onyile, Onyile",
  "Opoku, Samuel",
  "Orvis, Jeffery",
  "Orvis, Jessica",
  "Osborne, Tanesha",
  "Owens, Charles",
  "Palmer, Nathan",
  "Pandey, Laxman",
  "Parham, Abbie",
  "Parks, Fayth",
  "Pate, Stephen",
  "Patterson, Steven",
  "Payne, Malerie",
  "Peace, Karl",
  "Pearsall, Thomas",
  "Pearson, Timothy",
  "Pease, Aron",
  "Peden, John",
  "Pellegrino, Joseph",
  "Pemberton, Michael",
  "Peng, Juanjuan",
  "Penix, Kellie",
  "Perez, Alfredo",
  "Perez, Carolina",
  "Perry, Amy",
  "Petrosino, Krista",
  "Peyton, Benjamin",
  "Pfund, Celine",
  "Phillips, J.",
  "Phipps, Karen",
  "Pickens, Julie",
  "Piltner, Reinhard",
  "Pinilla-Herrera, Angela",
  "Pioske, Daniel",
  "Pirro, Robert",
  "Pitt, Eloise",
  "Plew, Melissa",
  "Plunkett, Chelsea",
  "Plunkett, Daniel",
  "Poindexter, Bianca",
  "Pollett, Jason",
  "Pool, Scot",
  "Posick, Chad",
  "Powell, Cecelia",
  "Powell, William",
  "Pritchard, Tony",
  "Pritham, Ursula",
  "Prude, M.",
  "Pruitt, Katherine",
  "Psonak, Kevin",
  "Pugh, Marion",
  "Pulliam, Christophe",
  "Pung, Oscar",
  "Purcell, Melissa",
  "Purcell, Roger",
  "Qin, Hantang",
  "Quarles, Dominique",
  "Quirino, Rafael",
  "Radko, Nicholas",
  "Radzyminski, Sharon",
  "Rahman, Mosfequr",
  "Ramoutar, Ria",
  "Randall, Cindy",
  "Randall, E.",
  "Rangel, Dolores",
  "Ransom, Marshall",
  "Rashidi, Abbas",
  "Rasnick, Elizabeth",
  "Rea, Dan",
  "Reagan, Julie",
  "Reichard, James",
  "Reid, Samantha",
  "Reidel, Michelle",
  "Ren, Xuchun",
  "Ressler, Rand",
  "Reynolds, William",
  "Rich, Fredrick",
  "Riggs, Amy",
  "Riggs, Rebecca",
  "Riley, Desiree",
  "Rios-Gutierrez, Fernando",
  "Roach, Susan",
  "Robb, Claire",
  "Robbins, Judith",
  "Roberts, Charity",
  "Roberts, Coco",
  "Roberts, Jamie",
  "Robichau, Robbie",
  "Rochani, Haresh",
  "Rocker, Karla",
  "Rodell, Paul",
  "Roell, Craig",
  "Rogers, Alfreda",
  "Rogers, Camille",
  "Rogers, Gerald",
  "Rogers, Peter",
  "Rollins, Minna",
  "Romanchik-Cerpovicz, Joelle",
  "Romero, Neri",
  "Ross, Levi",
  "Ross, Sabrina",
  "Rossetti, Christian",
  "Rossi, Stephen",
  "Rostal, David",
  "Roughton, Hubert",
  "Rousseau, Joseph",
  "Rousseau, Mary Beth",
  "Rowell, Amy",
  "Ruhland, Joseph",
  "Ruiz Funes, Marcela",
  "Rushing, Alison",
  "Rushton, Edward",
  "Rusina, Anastasia",
  "Rustin, Ronald",
  "Ryan, Courtney",
  "Ryan, Gregory",
  "Ryan, Rebecca",
  "Ryan, William",
  "Saenz-Ayala, Mariana",
  "Saha, Arpita",
  "Saha, Subhrajit",
  "Sala, Ryan",
  "Salekeen, Sirajus",
  "Salhi, Christina",
  "Salhi, Youssef",
  "Samanta, Biswanath",
  "Samawi, Hani",
  "Sanchez, Mauricio",
  "Sanders, Susan",
  "Sayed Ahmed, Adel",
  "Scalera, Jamie",
  "Scarborough, Amy",
  "Schanz, Hans-Jorg",
  "Schenk, John",
  "Schenk, Xizhen",
  "Schille, Candy",
  "Schiman, Jeffrey",
  "Schmid, Alice",
  "Schmid, William",
  "Schmuki, Jeffrey",
  "Schneider, Alfred",
  "Schott, David",
  "Schreiber, Joanna",
  "Schueths, April",
  "Schumacher, Amanda",
  "Scott, Angelita",
  "Scott, Elisabeth",
  "Scott, Heather",
  "Scott, Regina",
  "Seminatore, Gerald",
  "Sendall, Kerrie",
  "Sexton, Jared",
  "Shah, Gulzar",
  "Shaikh, Mohammed",
  "Shankar, Padmini",
  "Shapiro, Derek",
  "Shen, Junan",
  "Shepherd, C.",
  "Shepherd, Kathy",
  "Sheppard, Ronnie",
  "Shilling, Dellarie",
  "Shin, Hyunju",
  "Shin, Minchul",
  "Shrestha, Pooja",
  "Shumaker, Nancy",
  "Siddiquee, Intekhaab",
  "Siddiqui, Salman",
  "Sikora, David",
  "Sills, Andrew",
  "Silva, Eric",
  "Silwal, Bishal",
  "Simons, Jacob",
  "Simpara, Hope",
  "Simpson, Kimberly",
  "Sims, Anastatia",
  "Sipe, Stephanie",
  "Sittaramane, Vinoth",
  "Skidmore-Hess, Cathy",
  "Skipper, Alan",
  "Sleep, Stefan",
  "Slone, Donald",
  "Smalley, Kirbie",
  "Smallwood, Stacy",
  "Smalt, Steven",
  "Smith, Amy",
  "Smith, Chasen",
  "Smith, Christophe",
  "Smith, Danielle",
  "Smith, Earl",
  "Smith, Joyya",
  "Smith, Kathlyn",
  "Smith, Ralphel",
  "Smith, Reed",
  "Smith, Solomon",
  "Smith, William",
  "Sneathen, Lowell",
  "Snipes, Erica",
  "Soares, Lina",
  "Soloiu, Valentin",
  "Sood, Abha",
  "Spann, Britta",
  "Spearman, Jessica",
  "Spence, Alicia",
  "Staff, Unknown",
  "Stalcup, Lawrence",
  "Stambaugh, Laura",
  "Stapleton, Deborah",
  "Stefaniak, Lauren",
  "Steirn, Janice",
  "Stephens, James",
  "Stevenson, Alma",
  "Stewart, Amanda",
  "Stewart, Errol",
  "Stewart, Steven",
  "Stobb, Maureen",
  "Stokolos, Alexander",
  "Stone, David",
  "Stone, John",
  "Stone, Melanie",
  "Strauser, Beverly",
  "Stuart, Esther",
  "Stuart, Gloria",
  "Stumpf, Don",
  "Sturges, Diana",
  "Sturz, Bradley",
  "Suazo, Jorge",
  "Suboleski, Stanley",
  "Sullens, Donald",
  "Sullivan, Kelly",
  "Svec, Lace",
  "Swaim, James",
  "Sweeney, Kara",
  "Sweeney, Thomas",
  "Syno, Jennifer",
  "Syno, Matthew",
  "Tabatabaei, Manouchehr",
  "Tabi, Marian",
  "Tacy, Nelson",
  "Takas, Nathan",
  "Tang, Xiao",
  "Tarasenko, Yelena",
  "Taylor, Issac",
  "Taylor, Robert",
  "Taylor, Sharon",
  "Taylor, Timothy",
  "Teeter, Timothy",
  "Telfair, Joseph",
  "Thackston, Russell",
  "Tharp, Kelly",
  "Thomas, Katherine",
  "Thomas, Michael",
  "Thompson, Christina",
  "Thompson, John",
  "Thompson, Terry",
  "Thompson-Rogers, Rebecca",
  "Thomson, Douglass",
  "Thomson, Susan",
  "Thornton, Kathleen",
  "Todd, Robert",
  "Todd, Samuel",
  "Tolentino, Timothy",
  "Tong, Weitian",
  "Tookes, Jennifer L",
  "Tootle, Kathleen",
  "Town, Caren",
  "Townsend, Tiffanie",
  "Tremblay, Michelle",
  "Tu, Wei",
  "Turner, Wendell",
  "Tysinger, Jeffrey",
  "Tysinger, P.",
  "Tyson, Jenna",
  "Uchida, Masahiko",
  "Uchida, Namiko",
  "Unal, Aslihan",
  "Underwood, Stephen",
  "Valeri, Laura",
  "Van Sant, Claude",
  "Van Stan, John",
  "Van Tassell, Darin",
  "Van Wagenen, Michael",
  "Van Willigen, Marieke",
  "Vance, Lisa",
  "Vance, Robert",
  "Vargas, Juan",
  "Varnell, Jacqueline",
  "Villa-Vargas, Jorge",
  "Villeponteaux, Mary",
  "Viness, Stephanie",
  "Vives, Stephen",
  "Vlcek, Brian",
  "Vogel, Robert",
  "Wahl, Carly",
  "Wainford, Philis",
  "Waldrop, Phillip",
  "Walker, Janice",
  "Walker- DeVose, Dina",
  "Walker-Colquitt, Ashley",
  "Wall, Nancy",
  "Walsh, Clare",
  "Walton, Patricia",
  "Wanduku, Divine",
  "Wang, Hua",
  "Wang, Kai",
  "Wang, Xiao-Jun",
  "Wang, Xinfang",
  "Warchol, Tomasz",
  "Warren, Caysi",
  "Watkins, Elizabeth",
  "Watson, Leonard",
  "Weaver, Casey",
  "Weaver, John",
  "Webster, Daniel",
  "Welch, Julia",
  "Welford, Mark",
  "Wells, Pamela",
  "Wells, William",
  "Wentworth, Benjamin",
  "Wentz, Matthew",
  "Wheaton, Patrick",
  "Whelan, Timothy",
  "Whitesel, Mark",
  "Whitlock, Christine",
  "Wickramarachchi, Tharanga",
  "Wiggins, Michael",
  "Williams, Bobbie",
  "Williams, David",
  "Williams, Jason",
  "Williams, Leigh",
  "Williams, Susan",
  "Williams-Johnson, Meca",
  "Williamson, Matthew",
  "Wilson, Charles",
  "Wilson, Janie",
  "Wilson, Robin",
  "Wimmer, Hayden",
  "Winskie, Amy",
  "Withers, Nicole",
  "Wolfe, Brent",
  "Wood, Malcolm",
  "Woods, James",
  "Woodward, Shelley",
  "Worrell-Carlisle, Pamela",
  "Wu, Ji",
  "Wu, Tiehang",
  "Wu, Yan",
  "Xu, Shaowen",
  "Yancey, Candace",
  "Yang, Bill",
  "Yang, Jiaqin",
  "Yanochik, Mark",
  "Yarbrough, Robert",
  "Yemelyanov, Alexander",
  "Yenipazarli, Arda",
  "Yin, JingJing",
  "Youmans, Jennifer",
  "Young, Caroline",
  "Yu, Lili",
  "Yu, Wei",
  "Zhang, Aimao",
  "Zhang, Jian",
  "Zhang, Jing-Yuan",
  "Zhang, Pidi",
  "Zhang, Rongrong",
  "Zhang, Wen-Ran",
  "Zhang, Zuotang",
  "Zhao, Chunshan",
  "Zheng, Shijun",
  "Zhou, Xiaolu",
  "Zhu, Jiehua",
  "Ziegler, Francois",
  "Zinskie, Cordelia",
  "Zorotovich, Jennifer",
  "Zou, Yuting",
  "Zumbro, Emily",
  "Zwald, A.",
  "Booth, Larry",
  "Comerford, Kathleen",
  "Gallard, Alejandro",
  "Gatch, Delena",
  "Jones, Jillian",
  "Kalaani, Youakim",
  "Lugo, Francisco",
  "Ming, Weihua",
  "Sun, Jing",
  "Tedders, Stuart",
  "Tharp, Brent",
  "Ward, Patrick",
  "Welford, Theresa",
  "Whiter, Amy",
  "Akhtar, Shakil",
  "Bonfante, Ana",
  "Bright-Ragland, Margee",
  "Callender, Craig",
  "Dillard, Leigh",
  "Fietkau, Ronald",
  "Flaherty, Jennifer",
  "Koffman, Stacy",
  "Mattord, Herbert",
  "Mauldin, June",
  "Muth, Benita",
  "Nelson, Dave",
  "Robertson, Sally",
  "Young, Karen"];

var termToSession = {
  "201608" : {
    "1" : "Full Term (15-AUG-16 - 08-DEC-16)",
    "G01" : "Full Semester GeorgiaOnMyLine (15-AUG-16 - 03-DEC-16)",
    "G02" : "Short Session 1 GeorgiaOnMyLine (15-AUG-16 - 07-OCT-16)",
    "G03" : "Short Session 2 GeorgiaOnMyLine (10-OCT-16 - 06-DEC-16)",
    "P" : "PPB No Drop (15-AUG-16 - 08-DEC-16)",
    "X" : "No Drop Classes (15-AUG-16 - 08-DEC-16)"
},
  "201701" : {
    "1" : "Full Term (09-JAN-17 - 05-MAY-17)",
    "G01" : "Full Semester GeorgiaOnMyLine (09-JAN-17 - 27-APR-17)",
    "G02" : "Short Session 1 GeorgiaOnMyLine (09-JAN-17 - 03-MAR-17)",
    "G03" : "Short Session 2 GeorgiaOnMyLine (06-MAR-17 - 27-APR-17)",
    "P" : "PPB No Drop (09-JAN-17 - 05-MAY-17)",
    "X" : "No Drop Classes (09-JAN-17 - 05-MAY-17)"
},
  "201705" : {
    "A" : "Term A (15-MAY-17 - 15-JUN-17)",
    "LS" : "Learning Support (19-JUN-17 - 21-JUL-17)",
    "LX" : "No Drop Part of Term L (15-MAY-17 - 13-JUL-17)",
    "AX" : "No Drop Part of Term A (15-MAY-17 - 15-JUN-17)",
    "B" : "Term B (19-JUN-17 - 21-JUL-17)",
    "BX" : "No Drop Part of Term B (19-JUN-17 - 21-JUL-17)",
    "D" : "COBA and JPHCOPH (15-MAY-17 - 28-JUN-17)",
    "E" : "COE Graduate Classes (30-MAY-17 - 13-JUL-17)",
    "EI" : "Eagle Incentive Program (19-JUN-17 - 21-JUL-17)",
    "G01" : "Full Semester GeorgiaOnMyLine (09-MAY-17 - 13-JUL-17)",
    "L" : "Long Term (15-MAY-17 - 13-JUL-17)"  }
}